use_frameworks!

target 'FeedCollectionViewController_Example' do
  pod 'FeedCollectionViewController', :path => '../'
  pod 'IDMPhotoBrowser', :git => 'https://github.com/oliveroneill/IDMPhotoBrowser.git'
  pod 'ImageFeedCollectionViewController', :path => '../'

  target 'FeedCollectionViewController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
