use_frameworks!

target 'FeedCollectionViewController_Example' do
  pod 'FeedCollectionViewController', :path => '../'

  target 'FeedCollectionViewController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
